# Generated by Django 6.0.6 on 2026-06-24 20:07

import django.db.models.deletion
import rrhh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre_completo', models.CharField(max_length=180)),
                ('cargo', models.CharField(max_length=140)),
                ('tipo_contrato', models.CharField(choices=[('Planta', 'Planta'), ('Contrata', 'Contrata'), ('Honorarios', 'Honorarios'), ('Reemplazo', 'Reemplazo'), ('Otro', 'Otro')], max_length=30)),
                ('unidad', models.CharField(max_length=120)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='PermisoCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('Feriado legal', 'Feriado legal'), ('Permiso con goce de remuneraciones', 'Permiso con goce de remuneraciones'), ('Permiso sin goce de remuneraciones', 'Permiso sin goce de remuneraciones'), ('Devolucion de tiempo libre', 'Devolucion de tiempo libre'), ('Licencia medica', 'Licencia medica'), ('Comision de servicio', 'Comision de servicio'), ('Capacitacion', 'Capacitacion'), ('Otro permiso', 'Otro permiso')], max_length=60)),
                ('numero_dias', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('hora_desde', models.TimeField(blank=True, null=True)),
                ('hora_hasta', models.TimeField(blank=True, null=True)),
                ('dias_pendientes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_entrega_solicitante', models.DateField(blank=True, null=True)),
                ('fecha_recepcion_oficina_personal', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20)),
                ('nombre_capacitacion', models.CharField(blank=True, max_length=180)),
                ('institucion_organizadora', models.CharField(blank=True, max_length=180)),
                ('modalidad', models.CharField(blank=True, choices=[('Presencial', 'Presencial'), ('Online', 'Online'), ('Mixta', 'Mixta')], max_length=20)),
                ('lugar', models.CharField(blank=True, max_length=180)),
                ('observaciones_capacitacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='rrhh.funcionario')),
            ],
            options={
                'verbose_name': 'Permiso o capacitacion',
                'verbose_name_plural': 'Permisos y capacitaciones',
                'ordering': ['-fecha_desde', 'funcionario__nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='permisos/', validators=[rrhh.models.validar_adjunto_rrhh])),
                ('nombre', models.CharField(blank=True, max_length=180)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='rrhh.permisocapacitacion')),
            ],
            options={
                'verbose_name': 'Documento adjunto',
                'verbose_name_plural': 'Documentos adjuntos',
                'ordering': ['-subido_en'],
            },
        ),
    ]
